FORMAT: 1A
HOST: http://www.google.com

# schema
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)
    
    + Body

            {
            "api_key": "444",
            "master": true,
            "name": "OK",
            "added": "xxx"
            }
    + Schema
    
            {
            
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "Property System, Authentication, GET /advertisers Request",
            "type": "object",
                "properties": {
                    "api_key": {
                            "description": "The authentication key identifier for the advertiser making the request via the API",
                            "type": "string",
                            "minLength": 8,
                            "maxLength": 8,
                            "required": true
                        },
                    "master": {
                            "description": "The authentication key identifier for the advertiser making the request via the API",
                            "type": "boolean"
                        },
                    "name": {
                            "description": "The name of the new advertiser",
                            "type": "string",
                            "maxLength": 64,
                            "required": true
                        }
                }
            }

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
